set -g history-limit 100000

set -g extended-keys on
# set -g extended-keys-format csi-u # needs tmux 3.5+

set -g mouse on
set -g mode-keys vi

set -s set-clipboard on

# Use xclip to copy to system clipboard in copy-mode
# To maintain the scrollback position after copying, use `copy-pipe` instead of `copy-pipe-and-cancel`
bind -T copy-mode-vi y send-keys -X copy-pipe "xclip -selection clipboard -in"
bind -T copy-mode-vi Enter send-keys -X copy-pipe "xclip -selection clipboard -in"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -selection clipboard -in"

# For neomux
set-option -g escape-time 10
set-option -g focus-events on

# Switch to a pane AND instantly flash pane numbers as a guide
bind -n M-0 select-pane -t 0 \; display-panes
bind -n M-1 select-pane -t 1 \; display-panes
bind -n M-2 select-pane -t 2 \; display-panes
bind -n M-3 select-pane -t 3 \; display-panes
bind -n M-4 select-pane -t 4 \; display-panes
bind -n M-5 select-pane -t 5 \; display-panes
bind -n M-6 select-pane -t 6 \; display-panes
bind -n M-7 select-pane -t 7 \; display-panes
bind -n M-8 select-pane -t 8 \; display-panes
bind -n M-9 select-pane -t 9 \; display-panes

# Keep the number guide visible for 0.1 seconds after switching
set -g display-panes-time 100

# Customize the colours (Optional)
set -g display-panes-colour blue          # Colour for inactive panes
set -g display-panes-active-colour white  # Colour for the pane you just 

# Toggle pane zoom directly with Alt + z
bind -n M-z resize-pane -Z

# 1. Create a custom key table called 'window-switch' triggered by Alt+w
bind -n M-w switch-client -T window-switch

# 2. Define what happens when you press a number inside that table
bind -T window-switch 0 select-window -t 0
bind -T window-switch 1 select-window -t 1
bind -T window-switch 2 select-window -t 2
bind -T window-switch 3 select-window -t 3
bind -T window-switch 4 select-window -t 4
bind -T window-switch 5 select-window -t 5
bind -T window-switch 6 select-window -t 6
bind -T window-switch 7 select-window -t 7
bind -T window-switch 8 select-window -t 8
bind -T window-switch 9 select-window -t 9

# Enable pane titles on the top border
set -g pane-border-status top
set -g pane-border-format "#{pane_index} #T"

# Press Prefix + T to rename the current pane
bind T command-prompt -p "Panel Name:" "select-pane -T '%%'"

# synchronize-panes toggle, with indicator.
bind a setw synchronize-panes
setw -g window-status-current-format '#{?pane_synchronized,#[bg=red],}#I:#W#F' # the `#F` is to indicate the 'active window' i.e. *
setw -g window-status-format         '#{?pane_synchronized,#[bg=red],}#I:#W#F'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'kristopolous/tmux-gentrify'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

